/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as IndexRouteImport } from './routes/index'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/proposals': typeof ProposalsRoute
  '/request': typeof RequestRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/proposals': typeof ProposalsRoute
  '/request': typeof RequestRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/proposals': typeof ProposalsRoute
  '/request': typeof RequestRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm'
    | '/home'
    | '/login'
    | '/payment'
    | '/proposals'
    | '/request'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm'
    | '/home'
    | '/login'
    | '/payment'
    | '/proposals'
    | '/request'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/confirm'
    | '/home'
    | '/login'
    | '/payment'
    | '/proposals'
    | '/request'
    | '/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmRoute: typeof ConfirmRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  ProposalsRoute: typeof ProposalsRoute
  RequestRoute: typeof RequestRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmRoute: ConfirmRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  ProposalsRoute: ProposalsRoute,
  RequestRoute: RequestRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
